### ISSUE TITLE
TypeError: sequence item 0: expected string, NoneType found

### ISSUE THREAD

**Issue by LukasBeaton** [dailymuse/s3-content-type-fixer#14]
This library seems to be broken...

+ python ~/s3-content-type-fixer-master/s3_content_type_fixer.py --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --bucket adparlor.design
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/root/s3-content-type-fixer-master/s3_content_type_fixer.py", line 55, in check_headers
    key.copy(key.bucket, key.name, preserve_acl=True, metadata={'Content-Type': expected_content_type, 'Content-Disposition': key.content_disposition})
  File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 355, in copy
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 699, in copy_key
    query_args=query_args)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 470, in make_request
    override_num_retries=override_num_retries)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 913, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 793, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python2.7/httplib.py", line 946, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 986, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python2.7/httplib.py", line 924, in putheader
    str = '%s: %s' % (header, '\r\n\t'.join(values))
TypeError: sequence item 0: expected string, NoneType found
index.js: Current content type (text/plain) does not match expected (application/x-javascript); fixing`
`

**Comment by LukasBeaton** [comment]
Maybe the version of Python that I am using is not supported?

**Comment by ysimonson** [comment]
I just did a dry run in python 2.7 and it worked fine, so it's unlikely to be the version. Is your access key restricted in any way? If so, maybe it has something to do with that. I'm not sure - the error is coming from boto, so it's harder to diagnose.

**Comment by LukasBeaton** [comment]
Hey thanks for the quick reply!

I found the root cause of the issue is in s3_content_type_fixer.py on line 55.

```
key.copy(key.bucket, key.name, preserve_acl=True, metadata={'Content-Type': expected_content_type, 'Content-Disposition': key.content_disposition})
```

It appears that key.content_disposition is evaluating to None which causes an error further down the call stack. I updated line 55 to the following as a temporary workaround.

```
 key.copy(key.bucket, key.name, preserve_acl=True, metadata={'Content-Type': expected_content_type})
```

At the moment my access key is restricted to the following permissions on my bucket.
- "s3:GetObject"
- "s3:PutObject"
- "s3:GetObjectAcl"
- "s3:PutObjectAcl"
- "s3:DeleteObject"

**Comment by ysimonson** [comment]
That's necessary for people that want to preserve the content disposition: https://github.com/dailymuse/s3-content-type-fixer/pull/7

Maybe we could conditionally set it though.

**Comment by ysimonson** [comment]
@LukasBeaton this should be fixed now - could you test it out?
